- hosts: test_ec2
  gather_facts: true
  become: yes
  any_errors_fatal: true
  roles:
    - { role: debian-11, when: ansible_distribution == "Debian" }
    - { role: debian-12, when: ansible_distribution == "Debian" }
  tags:
    - docker